/*
 * 모델별 한글 설명 카탈로그.
 *
 * Venice.ai 공식 문서(https://docs.venice.ai/models/image · /models/video ·
 * /models/text-to-speech)와 공식 모델 카탈로그(veniceai/api-docs 의
 * data/static-models.json)를 근거로 작성했습니다. 모델 ID가 바뀌거나 새 모델이
 * 추가되면 API의 model_spec.description이 대신 사용됩니다.
 *
 * 채팅 모델(text)은 API 설명이 충실한 편이라 여기에 넣지 않고, 이미지·영상·
 * TTS 모델만 정리합니다.
 */

const MODEL_DESCRIPTIONS: Record<string, string> = {
  /* ---------------------------------------------------------- 이미지 */
  "wai-Illustrious": "애니메이션·일러스트 특화 모델(WAI). 2D 애니메이션 스타일의 일러스트와 캐릭터 이미지 생성에 강점을 가집니다.",
  "bria-bg-remover": "배경 제거 전용 모델. 인물·제품 사진의 배경을 자동으로 분리해 투명 이미지로 만들어 줍니다.",
  chroma: "색감과 조명 표현에 강한 포토리얼리스틱 이미지 생성 모델입니다.",
  "flux-2-max": "Black Forest Labs의 Flux 2 최상위 버전. 선명한 디테일과 자연스러운 텍스트 렌더링이 특징입니다.",
  "flux-2-pro": "Flux 2 프로 버전. 디테일 표현과 프롬프트 충실도의 균형을 잡은 고품질 생성 모델입니다.",
  "gpt-image-1-5": "OpenAI GPT Image 1.5. 풍부한 디테일과 자연어 프롬프트 이해에 강하며 quality(low/medium/high) 옵션을 지원합니다.",
  "gpt-image-2": "OpenAI GPT Image 2. 최신 GPT 이미지 모델로 고품질 생성·편집에 강하며 quality 옵션을 지원합니다.",
  "grok-imagine-image": "xAI의 Grok Imagine 이미지 생성 모델. 사실적인 사진 스타일과 창의적인 구도를 잘 만들어 냅니다.",
  "grok-imagine-image-2-0": "xAI Grok Imagine 2.0. 전 세대 대비 디테일과 프롬프트 충실도가 개선된 이미지 생성 모델입니다.",
  "grok-imagine-image-quality": "Grok Imagine 고품질(SOTA) 버전. 최고 품질의 이미지를 우선시할 때 사용합니다.",
  "hunyuan-image-v3": "텐센트 Hunyuan Image 3.0. 다국어·한자 텍스트 렌더링에 강하며 사실적 이미지 생성이 특징입니다.",
  "ideogram-v4": "Ideogram V4. 텍스트·로고·타이포그래피가 들어간 이미지 생성에 특화된 모델입니다.",
  "imagineart-1.5-pro": "ImagineArt 1.5 Pro. 다양한 아트 스타일을 창의적으로 생성하는 이미지 모델입니다.",
  "krea-2-turbo": "Krea 2 Turbo. 고속 생성에 최적화된 실사 품질 이미지 모델입니다.",
  "krea-v2-large": "Krea v2 Large. 포토리얼리스틱 품질에 중점을 둔 이미지 생성 모델입니다.",
  "krea-v2-medium": "Krea v2 Medium. 품질과 속도의 균형을 잡은 실사 이미지 생성 모델입니다.",
  "luma-uni-1": "Luma Uni-1. 사실적 사진부터 창의적 스타일까지 폭넓게 생성하는 이미지 모델입니다.",
  "luma-uni-1-max": "Luma Uni-1 Max. Uni-1의 최상위 품질 버전으로 디테일 표현에 강합니다.",
  "lustify-sdxl": "Lustify(Stable Diffusion XL 기반). 감성적이고 미적인 이미지 생성에 특화된 모델입니다.",
  "lustify-v7": "Lustify v7. 미적 스타일과 분위기 표현에 강한 이미지 생성 모델입니다.",
  "lustify-v8": "Lustify v8. 최신 Lustify 모델로 디테일과 스타일 표현이 개선되었습니다.",
  "nano-banana-2": "Google Nano Banana 2. 빠른 생성 속도와 aspect_ratio·resolution 파라미터를 지원하는 고품질 모델입니다.",
  "nano-banana-2-lite": "Nano Banana 2 Lite. 속도를 우선하는 경량 버전입니다.",
  "nano-banana-pro": "Nano Banana Pro. Nano Banana 계열의 프로 버전으로 품질을 우선합니다.",
  "qwen-image": "알리바바 Qwen Image. 폭넓은 스타일을 지원하며 width/height 픽셀 지정으로 생성합니다.",
  "qwen-image-2": "Qwen Image 2. aspect_ratio 기반 구도 지정과 고품질 생성이 특징입니다.",
  "qwen-image-2-pro": "Qwen Image 2 Pro. 프로 버전으로 해상도와 디테일이 개선되었습니다.",
  "qwen-image-3": "Qwen Image 3. 최신 세대로 1K/2K/4K 해상도 옵션을 지원합니다.",
  "qwen-image-3-pro": "Qwen Image 3 Pro. Qwen Image 3의 최상위 품질 버전입니다.",
  "recraft-v4": "Recraft V4. 일러스트·브랜드 디자인·벡터 스타일 생성에 강한 모델입니다.",
  "recraft-v4-pro": "Recraft V4 Pro. 디자인 품질을 우선하는 프로 버전입니다.",
  "seedream-v4": "ByteDance Seedream V4. 사실적인 디테일과 조명 표현에 강한 이미지 생성 모델입니다.",
  "seedream-v5-lite": "Seedream V5 Lite. 속도를 우선하는 경량 버전입니다.",
  "seedream-v5-pro": "Seedream V5 Pro. 최신 Seedream의 고품질 프로 버전입니다.",
  "venice-sd35": "Venice의 Stable Diffusion 3.5 기반 기본 이미지 모델. 넓은 호환성과 width/height 직접 지정을 지원합니다.",
  "wan-2-7-text-to-image": "Wan 2.7 텍스트-이미지 모델. 프롬프트 충실도 높은 고품질 생성을 지원합니다.",
  "wan-2-7-pro-text-to-image": "Wan 2.7 Pro 텍스트-이미지. 프로 품질로 디테일이 개선되었습니다.",
  "z-image-turbo": "Z-Image Turbo. 고속 생성에 최적화된 이미지 모델입니다.",

  /* ---------------------------------------------------------- 영상 */
  "flux-3-text-to-video": "Flux 3 텍스트-영상 모델. 프롬프트로 장면을 설명하면 영상으로 만들어 줍니다.",
  "flux-3-image-to-video": "Flux 3 이미지-영상 모델. 시작 이미지(image_url)를 주면 그 장면에서 이어지는 영상을 생성합니다.",
  "flux-3-first-last-frame-to-video": "Flux 3 첫·끝 프레임 지정 모델. 시작과 끝 장면을 지정해 그 사이를 자연스럽게 이어주는 영상을 만듭니다.",
  "gemini-omni-flash-text-to-video": "Google Gemini Omni Flash 텍스트-영상. 빠른 생성 속도가 특징입니다.",
  "gemini-omni-flash-image-to-video": "Gemini Omni Flash 이미지-영상. 시작 이미지를 받아 빠르게 영상을 생성합니다.",
  "gemini-omni-flash-reference-to-video": "Gemini Omni Flash R2V. 참조 이미지를 이용해 캐릭터·장면 일관성을 유지하는 영상 생성 모델입니다.",
  "grok-imagine-text-to-video-private": "xAI Grok Imagine 텍스트-영상. 프롬프트만으로 사실적인 영상을 생성합니다.",
  "grok-imagine-image-to-video-private": "Grok Imagine 이미지-영상. 시작 이미지에서 이어지는 영상을 생성합니다.",
  "grok-imagine-video-to-video-private": "Grok Imagine 영상-영상. 기존 영상의 스타일·동작을 바꿔 새 영상으로 만들어 줍니다.",
  "grok-imagine-1-5-text-to-video-private": "Grok Imagine 1.5 텍스트-영상. 차세대 Grok Imagine으로 모션 표현이 개선되었습니다.",
  "grok-imagine-1-5-image-to-video-private": "Grok Imagine 1.5 이미지-영상. 시작 이미지를 받아 자연스러운 움직임의 영상을 생성합니다.",
  "grok-imagine-1-5-reference-to-video-private": "Grok Imagine 1.5 R2V. 참조 이미지로 캐릭터·장면을 고정한 영상 생성 모델입니다.",
  "grok-imagine-reference-to-video-private": "Grok Imagine R2V. 참조 이미지를 활용해 일관성 있는 영상을 만드는 모델입니다.",
  "happyhorse-1-0-text-to-video": "HappyHorse 1.0 텍스트-영상. 얼굴·캐릭터 일관성에 강한 모델입니다.",
  "happyhorse-1-0-image-to-video": "HappyHorse 1.0 이미지-영상. 시작 이미지의 얼굴을 유지하며 영상을 생성합니다.",
  "happyhorse-1-0-video-to-video": "HappyHorse 1.0 Edit. 기존 영상을 받아 편집·변형하는 영상-영상 모델입니다.",
  "happyhorse-1-0-reference-to-video": "HappyHorse 1.0 Reference. 참조 이미지로 캐릭터를 고정하는 영상 생성 모델입니다.",
  "happyhorse-1-1-text-to-video": "HappyHorse 1.1 텍스트-영상. 1.0 대비 품질이 개선된 버전입니다.",
  "happyhorse-1-1-image-to-video": "HappyHorse 1.1 이미지-영상. 시작 이미지 기반 생성이 개선되었습니다.",
  "happyhorse-1-1-reference-to-video": "HappyHorse 1.1 Reference. 참조 이미지 기반 캐릭터 고정 성능이 개선되었습니다.",
  "kling-2.5-turbo-pro-text-to-video": "Kling 2.5 Turbo Pro 텍스트-영상. 고속·고품질의 실사 영상 생성 모델입니다.",
  "kling-2.5-turbo-pro-image-to-video": "Kling 2.5 Turbo Pro 이미지-영상. 시작 이미지를 받아 고속으로 영상을 생성합니다.",
  "kling-2.6-pro-text-to-video": "Kling 2.6 Pro 텍스트-영상. 최신 Kling으로 사실적 모션 표현이 특징입니다.",
  "kling-2.6-pro-image-to-video": "Kling 2.6 Pro 이미지-영상. 시작 이미지에서 이어지는 고품질 영상을 생성합니다.",
  "kling-o3-4k-text-to-video": "Kling O3 4K 텍스트-영상. 4K 해상도를 지원하는 최상위 품질 모델입니다.",
  "kling-o3-4k-image-to-video": "Kling O3 4K 이미지-영상. 시작 이미지를 4K 품질의 영상으로 만들어 줍니다.",
  "kling-o3-4k-reference-to-video": "Kling O3 4K R2V. 참조 이미지로 캐릭터·장면을 고정하는 4K 영상 생성 모델입니다.",
  "kling-o3-pro-text-to-video": "Kling O3 Pro 텍스트-영상. 프로 품질의 실사 영상 생성 모델입니다.",
  "kling-o3-pro-image-to-video": "Kling O3 Pro 이미지-영상. 시작 이미지 기반 프로 품질 영상 생성 모델입니다.",
  "kling-o3-pro-reference-to-video": "Kling O3 Pro R2V. 참조 이미지 기반 캐릭터 고정 영상 생성 모델입니다.",
  "kling-o3-standard-text-to-video": "Kling O3 Standard 텍스트-영상. 표준 품질 옵션의 실사 영상 생성 모델입니다.",
  "kling-o3-standard-image-to-video": "Kling O3 Standard 이미지-영상. 시작 이미지를 받는 표준 품질 영상 생성 모델입니다.",
  "kling-o3-standard-reference-to-video": "Kling O3 Standard R2V. 참조 이미지 기반 표준 품질 영상 생성 모델입니다.",
  "kling-v3-4k-text-to-video": "Kling V3 4K 텍스트-영상. 4K 해상도를 지원하는 영상 생성 모델입니다.",
  "kling-v3-4k-reference-to-video": "Kling V3 4K R2V. 참조 이미지로 캐릭터를 고정하는 4K 영상 생성 모델입니다.",
  "kling-v3-pro-text-to-video": "Kling V3 Pro 텍스트-영상. 고품질 실사 영상 생성에 강한 모델입니다.",
  "kling-v3-pro-image-to-video": "Kling V3 Pro 이미지-영상. 시작 이미지를 받는 프로 품질 영상 생성 모델입니다.",
  "kling-v3-pro-motion-control": "Kling V3 Pro Motion Control. 카메라·동작 제어에 특화된 영상 생성 모델입니다.",
  "kling-v3-standard-text-to-video": "Kling V3 Standard 텍스트-영상. 표준 품질의 영상 생성 모델입니다.",
  "kling-v3-standard-image-to-video": "Kling V3 Standard 이미지-영상. 시작 이미지 기반 표준 품질 영상 생성 모델입니다.",
  "kling-v3-standard-motion-control": "Kling V3 Standard Motion Control. 동작 제어를 지원하는 표준 품질 모델입니다.",
  "kling-v3-turbo-pro-text-to-video": "Kling V3 Turbo Pro 텍스트-영상. 고속·고품질 영상 생성 모델입니다.",
  "kling-v3-turbo-pro-image-to-video": "Kling V3 Turbo Pro 이미지-영상. 시작 이미지를 고속으로 영상화합니다.",
  "kling-v3-turbo-standard-text-to-video": "Kling V3 Turbo Standard 텍스트-영상. 고속 표준 품질 영상 생성 모델입니다.",
  "kling-v3-turbo-standard-image-to-video": "Kling V3 Turbo Standard 이미지-영상. 고속·표준 품질의 이미지-영상 모델입니다.",
  "longcat-distilled-image-to-video": "Longcat Distilled 이미지-영상. 경량화로 속도를 높인 영상 생성 모델입니다.",
  "longcat-distilled-text-to-video": "Longcat Distilled 텍스트-영상. 경량화된 고속 영상 생성 모델입니다.",
  "longcat-image-to-video": "Longcat Full Quality 이미지-영상. 4K 고품질 영상 생성 모델입니다.",
  "longcat-text-to-video": "Longcat Full Quality 텍스트-영상. 4K 고품질 영상 생성 모델입니다.",
  "ltx-2-v2-3-fast-image-to-video": "LTX Video 2.3 Fast 이미지-영상. 빠른 생성 속도에 최적화된 모델입니다.",
  "ltx-2-v2-3-fast-text-to-video": "LTX Video 2.3 Fast 텍스트-영상. 고속 생성 모델입니다.",
  "ltx-2-v2-3-full-image-to-video": "LTX Video 2.3 Full Quality 이미지-영상. 고품질 영상 생성 모델입니다.",
  "ltx-2-v2-3-full-text-to-video": "LTX Video 2.3 Full Quality 텍스트-영상. 고품질 영상 생성 모델입니다.",
  "ltx-2-5-fast-image-to-video": "LTX Video 2.5 Fast 이미지-영상. 최신 세대 고속 모델입니다.",
  "ltx-2-5-fast-text-to-video": "LTX Video 2.5 Fast 텍스트-영상. 최신 세대 고속 모델입니다.",
  "ltx-2-5-pro-image-to-video": "LTX Video 2.5 Pro 이미지-영상. 프로 품질 영상 생성 모델입니다.",
  "ltx-2-5-pro-text-to-video": "LTX Video 2.5 Pro 텍스트-영상. 프로 품질 영상 생성 모델입니다.",
  "minimax-h3-text-to-video": "MiniMax H3 텍스트-영상. 캐릭터 표현과 감정 연기가 자연스러운 모델입니다.",
  "minimax-h3-image-to-video": "MiniMax H3 이미지-영상. 시작 이미지 기반 영상 생성 모델입니다.",
  "minimax-h3-enhanced-text-to-video": "MiniMax H3 Enhanced 텍스트-영상. 품질이 강화된 버전입니다.",
  "minimax-h3-reference-to-video": "MiniMax H3 R2V. 참조 이미지로 캐릭터를 고정하는 영상 생성 모델입니다.",
  "minimax-h3-enhanced-reference-to-video": "MiniMax H3 R2V Enhanced. 참조 이미지 기반 고품질 영상 생성 모델입니다.",
  "ovi-image-to-video": "Ovi 이미지-영상 모델. 시작 이미지를 받아 영상을 생성합니다.",
  "pixverse-c1-text-to-video": "PixVerse C1 텍스트-영상. 사실적인 영상 생성 모델입니다.",
  "pixverse-c1-image-to-video": "PixVerse C1 이미지-영상. 시작 이미지 기반 영상 생성 모델입니다.",
  "pixverse-c1-reference-to-video": "PixVerse C1 R2V. 참조 이미지 기반 영상 생성 모델입니다.",
  "pixverse-c1-transition": "PixVerse C1 Transition. 두 장면을 자연스럽게 전환하는 영상 생성 모델입니다.",
  "pixverse-v5.6-text-to-video": "PixVerse v5.6 텍스트-영상. 최신 PixVerse 영상 생성 모델입니다.",
  "pixverse-v5.6-image-to-video": "PixVerse v5.6 이미지-영상. 시작 이미지 기반 영상 생성 모델입니다.",
  "pixverse-v5.6-transition": "PixVerse v5.6 Transition. 장면 전환 영상 생성 모델입니다.",
  "runway-gen4-turbo": "Runway Gen-4 Turbo. 고속으로 생성하는 실사 영상 모델입니다.",
  "runway-gen4-5": "Runway Gen-4.5. 사실적 모션과 디테일이 뛰어난 최신 모델입니다.",
  "runway-gen4-5-text": "Runway Gen-4.5 텍스트 전용. 프롬프트 기반 실사 영상 생성 모델입니다.",
  "seedance-1-5-pro-text-to-video-basic": "ByteDance Seedance 1.5 Pro 텍스트-영상. 사실적 모션 표현에 강한 모델입니다.",
  "seedance-1-5-pro-image-to-video-basic": "Seedance 1.5 Pro 이미지-영상. 시작 이미지 기반 영상 생성 모델입니다.",
  "seedance-2-0-text-to-video-basic": "Seedance 2.0 텍스트-영상. 차세대 Seedance 영상 생성 모델입니다.",
  "seedance-2-0-image-to-video-basic": "Seedance 2.0 이미지-영상. 시작 이미지 기반 영상 생성 모델입니다.",
  "seedance-2-0-fast-text-to-video-basic": "Seedance 2.0 Fast 텍스트-영상. 고속 생성 모델입니다.",
  "seedance-2-0-fast-image-to-video-basic": "Seedance 2.0 Fast 이미지-영상. 고속 영상 생성 모델입니다.",
  "seedance-2-0-fast-reference-to-video-basic": "Seedance 2.0 Fast R2V. 참조 이미지 기반 고속 영상 생성 모델입니다.",
  "seedance-2-0-mini-text-to-video-basic": "Seedance 2.0 Mini 텍스트-영상. 경량 고속 영상 생성 모델입니다.",
  "seedance-2-0-mini-image-to-video-basic": "Seedance 2.0 Mini 이미지-영상. 경량 고속 모델입니다.",
  "seedance-2-0-mini-reference-to-video-basic": "Seedance 2.0 Mini R2V. 참조 이미지 기반 경량 영상 생성 모델입니다.",
  "seedance-2-0-reference-to-video-basic": "Seedance 2.0 R2V. 참조 영상·이미지로 모션과 스타일을 이어받는 영상 생성 모델입니다.",
  "seedance-2-5-text-to-video-basic": "Seedance 2.5 텍스트-영상. 최신 Seedance 영상 생성 모델입니다.",
  "seedance-2-5-image-to-video-basic": "Seedance 2.5 이미지-영상. 시작 이미지 기반 최신 영상 생성 모델입니다.",
  "seedance-2-5-reference-to-video-basic": "Seedance 2.5 R2V. 참조 기반 캐릭터·장면 고정 영상 생성 모델입니다.",
  "sora-2-image-to-video": "OpenAI Sora 2 이미지-영상. 사실적 영상 생성 모델입니다.",
  "sora-2-text-to-video": "OpenAI Sora 2 텍스트-영상. 사실적 영상 생성 모델입니다.",
  "sora-2-pro-image-to-video": "Sora 2 Pro 이미지-영상. 프로 품질 영상 생성 모델입니다.",
  "sora-2-pro-text-to-video": "Sora 2 Pro 텍스트-영상. 프로 품질 영상 생성 모델입니다.",
  "topaz-video-upscale": "Topaz Video Upscale. 기존 영상을 2x/4x 해상도로 업스케일하거나 품질을 강화하는 전용 모델입니다.",
  "veo3-fast-text-to-video": "Google Veo 3 Fast 텍스트-영상. 빠른 생성 속도의 영상 모델입니다.",
  "veo3-fast-image-to-video": "Veo 3 Fast 이미지-영상. 시작 이미지 기반 고속 영상 생성 모델입니다.",
  "veo3-full-text-to-video": "Veo 3 Full Quality 텍스트-영상. 자연스러운 모션의 고품질 영상 모델입니다.",
  "veo3-full-image-to-video": "Veo 3 Full Quality 이미지-영상. 시작 이미지 기반 고품질 영상 모델입니다.",
  "veo3.1-fast-text-to-video": "Veo 3.1 Fast 텍스트-영상. 최신 Veo 고속 영상 생성 모델입니다.",
  "veo3.1-fast-image-to-video": "Veo 3.1 Fast 이미지-영상. 최신 Veo 고속 영상 생성 모델입니다.",
  "veo3.1-full-text-to-video": "Veo 3.1 Full Quality 텍스트-영상. 최신 Veo 고품질 영상 생성 모델입니다.",
  "veo3.1-full-image-to-video": "Veo 3.1 Full Quality 이미지-영상. 최신 Veo 고품질 영상 생성 모델입니다.",
  "vidu-q3-text-to-video": "Vidu Q3 텍스트-영상. 고품질 영상 생성 모델입니다.",
  "vidu-q3-image-to-video": "Vidu Q3 이미지-영상. 시작 이미지 기반 영상 생성 모델입니다.",
  "wan-2.1-pro-image-to-video": "Wan 2.1 Pro 이미지-영상. 프로 품질 영상 생성 모델입니다.",
  "wan-2.2-a14b-text-to-video": "Wan 2.2 A14B 텍스트-영상. A14B 아키텍처 기반 영상 생성 모델입니다.",
  "wan-2-2-enhanced-image-to-video": "Wan 2.2 Enhanced 이미지-영상. 품질이 강화된 영상 생성 모델입니다.",
  "wan-2.5-preview-image-to-video": "Wan 2.5 Preview 이미지-영상. 프리뷰 버전 영상 생성 모델입니다.",
  "wan-2.5-preview-text-to-video": "Wan 2.5 Preview 텍스트-영상. 프리뷰 버전 영상 생성 모델입니다.",
  "wan-2.6-image-to-video": "Wan 2.6 이미지-영상. 최신 Wan 영상 생성 모델입니다.",
  "wan-2.6-text-to-video": "Wan 2.6 텍스트-영상. 최신 Wan 영상 생성 모델입니다.",
  "wan-2.6-flash-image-to-video": "Wan 2.6 Flash 이미지-영상. 고속 생성에 최적화된 모델입니다.",
  "wan-2-7-text-to-video": "Wan 2.7 텍스트-영상. 최신 Wan 영상 생성 모델입니다.",
  "wan-2-7-image-to-video": "Wan 2.7 이미지-영상. 시작 이미지 기반 영상 생성 모델입니다.",
  "wan-2-7-video-to-video": "Wan 2.7 Edit. 기존 영상을 받아 편집·변형하는 영상-영상 모델입니다.",
  "wan-2-7-enhanced-image-to-video": "Wan 2.7 Enhanced 이미지-영상. 품질 강화 버전입니다.",
  "wan-2-7-enhanced-text-to-video": "Wan 2.7 Enhanced 텍스트-영상. 품질 강화 버전입니다.",
  "wan-2-7-reference-to-video": "Wan 2.7 Reference. 참조 이미지로 캐릭터·장면을 고정하는 영상 생성 모델입니다.",

  /* ---------------------------------------------------------- TTS */
  "tts-kokoro": "Kokoro 텍스트-음성 모델. 가볍고 빠른 기본 TTS로 다국어 목소리(af_sky, af_bella, am_adam 등)를 지원합니다.",
  "tts-qwen3-0-6b": "Qwen 3 TTS 0.6B. 감정·말투를 지정하는 스타일 프롬프트를 지원하는 경량 TTS 모델입니다.",
  "tts-qwen3-1-7b": "Qwen 3 TTS 1.7B. 감정·말투 스타일 프롬프트를 지원하는 고품질 TTS 모델입니다.",
  "tts-xai-v1": "xAI TTS v1. 26개의 목소리(eve, ara, rex 등)를 제공하는 텍스트-음성 모델입니다.",
  "tts-inworld-1-5-max": "Inworld TTS-1.5 Max. 자연스러운 대화형 음성 생성에 강한 TTS 모델입니다.",
  "tts-chatterbox-hd": "Chatterbox HD(Resemble AI). 짧은 샘플만으로 목소리를 복제하는 보이스 클로닝을 지원하는 TTS 모델입니다.",
  "tts-orpheus": "Orpheus TTS. 감정 표현이 풍부한 목소리(tara, leah, jess, leo 등)를 제공합니다.",
  "tts-elevenlabs-turbo-v2-5": "ElevenLabs Turbo v2.5. 자연스러운 음성 합성에 강한 고속 TTS 모델입니다.",
  "tts-minimax-speech-02-hd": "MiniMax Speech-02 HD. 고품질 음성 합성 TTS 모델입니다.",
  "tts-gemini-3-1-flash": "Gemini 3.1 Flash TTS. 빠른 생성 속도의 텍스트-음성 모델입니다.",
  "tts-gradium-v1": "Gradium TTS. 영어·독일어·프랑스어·스페인어·포르투갈어·이탈리아어 등 다국어 목소리를 지원합니다.",
};

export function modelDescription(modelId: string): string | null {
  return MODEL_DESCRIPTIONS[modelId] ?? null;
}